//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TblUser
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [RegularExpression(@"^[A-Z][a-z]*(\s[A-Z][a-z]*)+$", ErrorMessage = "Not a valid name!")]
        [Display(Name = "Full Name")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [EmailAddress]
        [DataType(DataType.EmailAddress)]

        [Display(Name = "Email")]
        public string UserEmail { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Not a valid phone number!")]

        public string UserPhone { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [Display(Name = "Address")]
        public string UserAddress { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [Display(Name = "Confirm Password")]
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.Password)]
        [Compare("UserPassword", ErrorMessage = "Password and Confirmation Password must match!")]
        [NotMapped]
        public string RePassword { get; set; }
    }

}
